# Generated by Django 5.2.3 on 2025-07-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_author_alter_bookimage_book_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('A', 'AVAILABLE'), ('B', 'BORROWED'), ('M', 'MAINTENANCE')], default='A', max_length=1),
        ),
    ]
