# Generated by Django 5.2.3 on 2025-07-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_author_alter_bookimage_book_alter_book_author'),
        ('user', '0002_alter_author_dod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
